//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : Account.cpp
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#include "Account.h"
#include "Bid.h"

void Account::setBid(Bid theBid) {

}

int Account::calcAsset() {

}

