//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : Bid.cpp
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#include "Bid.h"

void Bid::setFund(Fund* theUnit) {

}

