//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : Bid.h
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#if !defined(_BID_H)
#define _BID_H

#include "Fund.h"

class Bid {
public:
	void setFund(Fund* theUnit);
	virtual int calcAsset() = 0;
	virtual float getUnit() = 0;
protected:
	Fund *fundObj;
};

#endif  //_BID_H
