//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : BidItem.cpp
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#include "BidItem.h"

BidItem::BidItem(float theUnit) {

}

float BidItem::getUnit() {

}

void BidItem::dd () {

}

