//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : BidItem.h
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#if !defined(_BIDITEM_H)
#define _BIDITEM_H


class BidItem {
public:
	BidItem(float theUnit);
	float getUnit();
	void dd ();
private:
	float unit;
};

#endif  //_BIDITEM_H
