//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : Fund.h
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#if !defined(_FUND_H)
#define _FUND_H


class Fund {
public:
	Fund(float thePrice);
	float getPrice();
private:
	float price;
};

#endif  //_FUND_H
