//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : Fund.cpp
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#include "Fund.h"

Fund::Fund(float thePrice) {

}

float Fund::getPrice() {

}

