//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : RegularBid.h
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#if !defined(_REGULARBID_H)
#define _REGULARBID_H

#include "Bid.h"

class RegularBid : public Bid {
public:
	RegularBid();
	int calcAsset();
	float getUnit();
	int calcAsset();
	float getUnit();
private:
	vector<BidItem*> itemObj;
};

#endif  //_REGULARBID_H
