//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : RegularBid.cpp
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#include "RegularBid.h"

RegularBid::RegularBid() {

}

int RegularBid::calcAsset() {

}

float RegularBid::getUnit() {

}

int RegularBid::calcAsset() {

}

float RegularBid::getUnit() {

}

