//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : SingleBid.cpp
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#include "SingleBid.h"

SingleBid::SingleBid(float theUnit) {

}

int SingleBid::calcAsset() {

}

float SingleBid::getUnit() {

}

int SingleBid::calcAsset() {

}

float SingleBid::getUnit() {

}

