//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : UML Sequence Diagram
//  @ File Name : SingleBid.h
//  @ Date : 2016/11/20
//  @ Author : 
//
//


#if !defined(_SINGLEBID_H)
#define _SINGLEBID_H

#include "Bid.h"

class SingleBid : public Bid {
public:
	SingleBid(float theUnit);
	int calcAsset();
	float getUnit();
	int calcAsset();
	float getUnit();
private:
	float unit;
};

#endif  //_SINGLEBID_H
